In [23]:
!pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [24]:
import pandas as pd
import numpy as np
import mysql.connector

In [25]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in .\.venv\Lib\site-packages (26.7.0)

In [39]:
# Load CSV
df = pd.read_csv("UPI TRANSACTION AND FRAUD DETECTION.csv")

In [40]:
# Clean data
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [41]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="0912"
)

cursor = connection.cursor()

print("MySQL connected successfully!")

MySQL connected successfully!

In [42]:
try:
    connection.close()
except:
    pass

In [43]:
# Create table (example)
import mysql.connector

# MySQL se connect
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="0912"
)

cursor = connection.cursor()

# Database create karo
cursor.execute("CREATE DATABASE IF NOT EXISTS upi_fraud")

# Database select karo
cursor.execute("USE upi_fraud")

# Check karo kaunsa database select hua
cursor.execute("SELECT DATABASE()")
print(cursor.fetchone())

# Table create karo
cursor.execute("""
CREATE TABLE IF NOT EXISTS transactions (
    txn_id VARCHAR(50),
    user_id VARCHAR(50),
    amount DECIMAL(10,2)
)
""")

connection.commit()
print("Table created successfully!")

('upi_fraud',)
Table created successfully!

In [44]:
#Create the transactions table
cursor.execute("""
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id VARCHAR(50),
    timestamp DATETIME,
    transaction_type VARCHAR(50),
    merchant_category VARCHAR(100),
    amount DECIMAL(10,2),
    transaction_status VARCHAR(50),
    sender_age_group VARCHAR(20),
    receiver_age_group VARCHAR(20),
    sender_state VARCHAR(50),
    sender_bank VARCHAR(100),
    receiver_bank VARCHAR(100),
    device_type VARCHAR(50),
    network_type VARCHAR(50),
    fraud_flag INT,
    hour_of_day INT,
    day_of_week VARCHAR(20),
    is_weekend BOOLEAN
)
""")

connection.commit()
print("Transactions table created successfully!")

Transactions table created successfully!

In [45]:
#Step 4: Check that the table was created
cursor.execute("SHOW TABLES")
print(cursor.fetchall())

[('transactions',)]

In [54]:
#Step 5: Read the CSV
import pandas as pd

df = pd.read_csv(r"C:\\Users\\Hp\\Downloads\\UPI TRANSACTION AND FRAUD DETECTION.csv")

In [56]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,8/10/2024 15:17,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,11/4/2024 6:56,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2/4/2024 13:27,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,7/1/2024 10:09,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,23-01-2024 19:04,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [58]:
df.tail(2)

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
249998,TXN0000249999,5/1/2024 13:31,Recharge,Healthcare,284,SUCCESS,18-25,36-45,Andhra Pradesh,Axis,ICICI,iOS,4G,0,13,Friday,0
249999,TXN0000250000,17-01-2024 15:23,P2P,Entertainment,531,SUCCESS,18-25,26-35,Telangana,Axis,Yes Bank,Android,4G,0,15,Wednesday,0

In [49]:
print(df.columns)

Index(['transaction id', 'timestamp', 'transaction type', 'merchant_category',
       'amount (INR)', 'transaction_status', 'sender_age_group',
       'receiver_age_group', 'sender_state', 'sender_bank', 'receiver_bank',
       'device_type', 'network_type', 'fraud_flag', 'hour_of_day',
       'day_of_week', 'is_weekend'],
      dtype='str')

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  str
 1   timestamp           250000 non-null  str
 2   transaction type    250000 non-null  str
 3   merchant_category   250000 non-null  str
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  str
 6   sender_age_group    250000 non-null  str
 7   receiver_age_group  250000 non-null  str
 8   sender_state        250000 non-null  str
 9   sender_bank         250000 non-null  str
 10  receiver_bank       250000 non-null  str
 11  device_type         250000 non-null  str
 12  network_type        250000 non-null  str
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  str
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), str(13)
memory usage: 32.4 MB

In [ ]:
# Check first 10 timestamp values
print(df["timestamp"].head(10))

0     8/10/2024 15:17
1      11/4/2024 6:56
2      2/4/2024 13:27
3      7/1/2024 10:09
4    23-01-2024 19:04
5     7/10/2024 22:32
6      8/2/2024 10:25
7    27-10-2024 18:47
8    21-11-2024 09:39
9    11/11/2024 15:58
Name: timestamp, dtype: str

In [ ]:
#Step 6: Convert the timestamp

df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    format="mixed",      #To handle mixed date formats 
    errors="coerce"      
)

In [63]:
print(df["timestamp"].dtype)
print(df["timestamp"].isna().sum())

datetime64[us]
0

In [64]:
print(df["timestamp"].head(20))
print(df["timestamp"].dtype)

0    2024-08-10 15:17:00
1    2024-11-04 06:56:00
2    2024-02-04 13:27:00
3    2024-07-01 10:09:00
4    2024-01-23 19:04:00
5    2024-07-10 22:32:00
6    2024-08-02 10:25:00
7    2024-10-27 18:47:00
8    2024-11-21 09:39:00
9    2024-11-11 15:58:00
10   2024-07-04 20:14:00
11   2024-12-24 10:44:00
12   2024-11-16 20:09:00
13   2024-10-04 00:51:00
14   2024-03-02 12:35:00
15   2024-09-11 15:21:00
16   2024-01-25 07:27:00
17   2024-05-19 18:38:00
18   2024-11-11 22:08:00
19   2024-06-13 18:25:00
Name: timestamp, dtype: datetime64[us]
datetime64[us]

Step 7: Data MySQL mein insert karo

In [65]:
print(df.columns.tolist())

['transaction id', 'timestamp', 'transaction type', 'merchant_category', 'amount (INR)', 'transaction_status', 'sender_age_group', 'receiver_age_group', 'sender_state', 'sender_bank', 'receiver_bank', 'device_type', 'network_type', 'fraud_flag', 'hour_of_day', 'day_of_week', 'is_weekend']

In [69]:
cursor.execute("DESCRIBE transactions")

for row in cursor.fetchall():
    print(row)

('txn_id', 'varchar(50)', 'YES', '', None, '')
('user_id', 'varchar(50)', 'YES', '', None, '')
('amount', 'decimal(10,2)', 'YES', '', None, '')

In [71]:
cursor.execute("DROP TABLE IF EXISTS transactions")
connection.commit()

print("Old transactions table deleted.")

Old transactions table deleted.

In [72]:
cursor.execute("""
CREATE TABLE transactions (
    transaction_id VARCHAR(100),
    timestamp DATETIME,
    transaction_type VARCHAR(50),
    merchant_category VARCHAR(100),
    amount DECIMAL(15,2),
    transaction_status VARCHAR(50),
    sender_age_group VARCHAR(50),
    receiver_age_group VARCHAR(50),
    sender_state VARCHAR(100),
    sender_bank VARCHAR(100),
    receiver_bank VARCHAR(100),
    device_type VARCHAR(50),
    network_type VARCHAR(50),
    fraud_flag INT,
    hour_of_day INT,
    day_of_week VARCHAR(20),
    is_weekend BOOLEAN
)
""")

connection.commit()

print("✅ New transactions table created!")

✅ New transactions table created!

In [ ]:
query = """
INSERT INTO transactions (
    transaction_id,
    timestamp,
    transaction_type,
    merchant_category,
    amount,
    transaction_status,
    sender_age_group,
    receiver_age_group,
    sender_state,
    sender_bank,
    receiver_bank,
    device_type,
    network_type,
    fraud_flag,
    hour_of_day,
    day_of_week,
    is_weekend
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

for _, row in df.iterrows():
    cursor.execute(query, 
        (row["transaction id"],       # CSV column has a space
        row["timestamp"].to_pydatetime() if pd.notna(row["timestamp"]) else None,
        row["transaction type"],      # CSV column has a space
        row["merchant_category"],
        float(row["amount (INR)"]),
        row["transaction_status"],
        row["sender_age_group"],
        row["receiver_age_group"],
        row["sender_state"],
        row["sender_bank"],
        row["receiver_bank"],
        row["device_type"],
        row["network_type"],
        int(row["fraud_flag"]),
        int(row["hour_of_day"]),
        row["day_of_week"],
        bool(row["is_weekend"])
    ))

connection.commit()

print("✅ All data inserted successfully!")